### ISSUE TITLE
dev build fails for ios (eas cli)

### ISSUE THREAD

**Issue by di-sukharev** [hyochan/expo-iap#127]
**Description**

```
› Executing expo-modules-core Pods/ExpoModulesCore » Copy generated compatibility header


❌  (../../node_modules/expo-iap/ios/ExpoIapModule.swift:297:65)

  295 |                 
  296 |                 if #available(iOS 18.4, *) {
> 297 |                     result["appTransactionID"] = appTransaction.appTransactionID
      |                                                                 ^ value of type 'AppTransaction' has no member 'appTransactionID'
  298 |                     result["originalPlatform"] = appTransaction.originalPlatform.rawValue
  299 |                 }
  300 |                 

    Run script build phase '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'hermes-engine' from project 'Pods')

    Run script build phase '[CP-User] [RN]Check rncore' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-FabricComponents' from project 'Pods')

    Run script build phase '[CP-User] [RN]Check rncore' will be run during every build because it does not specify any outputs. To address this issue, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Fabric' from project 'Pods')

▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	SwiftCompile normal arm64 Compiling\ ExpoIapModule.swift,\ ProductStore.swift,\ Types.swift /Users/expo/workingdir/build/node_modules/expo-iap/ios/ExpoIapModule.swift /Users/expo/workingdir/build/node_modules/expo-iap/ios/ProductStore.swift /Users/expo/workingdir/build/node_modules/expo-iap/ios/Types.swift (in target 'ExpoIap' from project 'Pods')

▸ 	CompileSwift normal arm64 (in target 'ExpoIap' from project 'Pods')

▸ 	Archiving workspace wprclient with scheme wprclient

▸ (3 failures)

** ARCHIVE FAILED **
```

**Expected Behavior**

works fine and build the eas expo dev build

**Screenshots**

<img width="1247" height="1042" alt="Image" src="https://github.com/user-attachments/assets/66290803-0842-409c-85ef-60d5fbf71dc5" />

**Environment:**

- expo-iap: 2.7.5
- react-native: 0.76.5 or 0.80.2, both fail
- Platforms (iOS, Android, emulator, simulator, device): ios
- Xcode version: 16.4
- ios target: cant even build it to run

**To Reproduce** Steps to reproduce the behavior:

1. run `eas build --profile development --platform ios --clear-cache`
2. get the error

**Comment by di-sukharev** [comment]
@hyochan looks like a duplicate of https://github.com/hyochan/expo-iap/issues/114, but the #114 is closed, yet i still get the error

**Comment by di-sukharev** [comment]
when updating react-native from 0.76.5 to 0.80.2 i get this error:
```
Build failed: The "Run fastlane" step failed because of an error in the Xcode build process. We automatically detected following errors in your Xcode build logs:
- no member named 'unit' in 'facebook::yoga::StyleLength'
- no member named 'unit' in 'facebook::yoga::StyleLength'
Refer to "Xcode Logs" below for additional, more detailed logs
```

**Comment by hyochan** [comment]
Thank you for conducting the experiment on fatigue. I've added document in faq.

Closes via 63965cec441c49af6dca83419ea3b76215ec34d9
